# Combined test script that loads ALL component test widgets.
# Start with: dh serve tests/scripts/components/all_components.py --port 10000

# Import all component test modules
exec(open("tests/scripts/components/test_button.py").read())
exec(open("tests/scripts/components/test_text_inputs.py").read())
exec(open("tests/scripts/components/test_pickers.py").read())
exec(open("tests/scripts/components/test_checkboxes.py").read())
exec(open("tests/scripts/components/test_sliders.py").read())
exec(open("tests/scripts/components/test_date_time.py").read())
exec(open("tests/scripts/components/test_layout.py").read())
exec(open("tests/scripts/components/test_display.py").read())
exec(open("tests/scripts/components/test_meter_progress.py").read())
exec(open("tests/scripts/components/test_tabs.py").read())
exec(open("tests/scripts/components/test_dialog.py").read())
exec(open("tests/scripts/components/test_menu.py").read())
exec(open("tests/scripts/components/test_list_view.py").read())
exec(open("tests/scripts/components/test_form.py").read())
exec(open("tests/scripts/components/test_disclosure.py").read())
exec(open("tests/scripts/components/test_links_nav.py").read())
exec(open("tests/scripts/components/test_contextual_help.py").read())
exec(open("tests/scripts/components/test_tag_group.py").read())
exec(open("tests/scripts/components/test_inline_alert.py").read())
exec(open("tests/scripts/components/test_accordion.py").read())
exec(open("tests/scripts/components/test_table.py").read())
exec(open("tests/scripts/components/test_markdown.py").read())
exec(open("tests/scripts/components/test_color_picker.py").read())
exec(open("tests/scripts/components/test_toast.py").read())
exec(open("tests/scripts/components/test_fragment.py").read())
exec(open("tests/scripts/components/test_panel.py").read())
exec(open("tests/scripts/components/test_html.py").read())
exec(open("tests/scripts/components/test_complex_interaction.py").read())
